pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven { url = uri('https://www.jetbrains.com/intellij-repository/releases') }
        maven { url = uri('https://cache-redirector.jetbrains.com/intellij-dependencies') }
    }
}

rootProject.name = 'sql-performance-analyzer-idea-plugin'
