-- H2 clean-install baseline (docs/cloud-code-next-goal.md §3.5).
--
-- Expresses a schema EQUIVALENT to the PostgreSQL target schema produced by the immutable
-- deployed history (versions 2..7): the same 27 product tables in the sql_analyzer schema under
-- the same version-less names, columns, primary/foreign keys, CHECK constraints and business
-- indexes. Portable forward migrations in db/migration-common (version 8+) apply identically on
-- top of this baseline and on top of the PostgreSQL history; SchemaParityTest freezes the
-- equivalence. Vendor notes: TIMESTAMPTZ -> TIMESTAMP WITH TIME ZONE, BIGSERIAL -> IDENTITY,
-- BYTEA -> BLOB. This file must never receive product changes after release: new objects go into
-- a portable common migration whenever possible.

CREATE SCHEMA IF NOT EXISTS sql_analyzer;

-- ---------- Client identity ----------

CREATE TABLE sql_analyzer.client (
    id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    type VARCHAR(50) NOT NULL,
    device_id VARCHAR(200),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE sql_analyzer.client_token (
    id VARCHAR(64) PRIMARY KEY,
    client_id VARCHAR(64) NOT NULL REFERENCES sql_analyzer.client(id),
    token_hash CHAR(64) NOT NULL UNIQUE,
    token_prefix VARCHAR(24) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_used_at TIMESTAMP WITH TIME ZONE,
    expires_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_client_token_active ON sql_analyzer.client_token(token_hash, status);

-- ---------- Sessions / messages ----------

CREATE TABLE sql_analyzer.analysis_session (
    id VARCHAR(64) PRIMARY KEY,
    client_id VARCHAR(64) NOT NULL REFERENCES sql_analyzer.client(id),
    title VARCHAR(300) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_session_client_updated ON sql_analyzer.analysis_session(client_id, updated_at DESC);

CREATE TABLE sql_analyzer.conversation_message (
    id VARCHAR(64) PRIMARY KEY,
    session_id VARCHAR(64) NOT NULL REFERENCES sql_analyzer.analysis_session(id),
    role VARCHAR(20) NOT NULL,
    content TEXT NOT NULL,
    message_type VARCHAR(50) NOT NULL DEFAULT 'TEXT',
    run_id VARCHAR(64),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_message_session_created ON sql_analyzer.conversation_message(session_id, created_at);

-- ---------- Agent runs / jobs / events ----------

CREATE TABLE sql_analyzer.agent_run (
    id VARCHAR(64) PRIMARY KEY,
    session_id VARCHAR(64) NOT NULL REFERENCES sql_analyzer.analysis_session(id),
    status VARCHAR(30) NOT NULL DEFAULT 'QUEUED',
    model_name VARCHAR(200),
    context_snapshot_id VARCHAR(64),
    error TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE sql_analyzer.agent_job (
    id VARCHAR(64) PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL REFERENCES sql_analyzer.agent_run(id),
    status VARCHAR(30) NOT NULL DEFAULT 'QUEUED',
    payload TEXT NOT NULL DEFAULT '{}',
    leased_by VARCHAR(200),
    lease_until TIMESTAMP WITH TIME ZONE,
    retry_count INTEGER NOT NULL DEFAULT 0,
    last_error TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_job_poll ON sql_analyzer.agent_job(status, created_at);

CREATE TABLE sql_analyzer.run_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL REFERENCES sql_analyzer.agent_run(id),
    type VARCHAR(80) NOT NULL,
    payload TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_run_event_run_id ON sql_analyzer.run_event(run_id, id);

-- ---------- Artifacts / documents ----------

CREATE TABLE sql_analyzer.artifact (
    id VARCHAR(64) PRIMARY KEY,
    client_id VARCHAR(64) NOT NULL REFERENCES sql_analyzer.client(id),
    session_id VARCHAR(64) REFERENCES sql_analyzer.analysis_session(id),
    source_type VARCHAR(50) NOT NULL,
    file_name VARCHAR(500),
    media_type VARCHAR(200),
    sha256 CHAR(64) NOT NULL,
    byte_size BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'INGESTED',
    metadata TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_artifact_client_created ON sql_analyzer.artifact(client_id, created_at DESC);

CREATE TABLE sql_analyzer.artifact_content (
    artifact_id VARCHAR(64) NOT NULL REFERENCES sql_analyzer.artifact(id) ON DELETE CASCADE,
    sequence_no INTEGER NOT NULL,
    content BLOB NOT NULL,
    PRIMARY KEY (artifact_id, sequence_no)
);

CREATE TABLE sql_analyzer.document (
    id VARCHAR(64) PRIMARY KEY,
    artifact_id VARCHAR(64) NOT NULL REFERENCES sql_analyzer.artifact(id),
    document_type VARCHAR(80) NOT NULL,
    parser_name VARCHAR(120) NOT NULL,
    parser_version VARCHAR(40) NOT NULL,
    normalized_text TEXT NOT NULL,
    structured_data TEXT NOT NULL DEFAULT '{}',
    status VARCHAR(30) NOT NULL DEFAULT 'PARSED',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sql_analyzer.document_chunk (
    id VARCHAR(64) PRIMARY KEY,
    document_id VARCHAR(64) NOT NULL REFERENCES sql_analyzer.document(id) ON DELETE CASCADE,
    sequence_no INTEGER NOT NULL,
    chunk_type VARCHAR(80) NOT NULL,
    content TEXT NOT NULL,
    token_count INTEGER NOT NULL DEFAULT 0,
    metadata TEXT NOT NULL DEFAULT '{}',
    UNIQUE(document_id, sequence_no)
);

-- ---------- Recommendations ----------

CREATE TABLE sql_analyzer.recommendation (
    id VARCHAR(64) PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL REFERENCES sql_analyzer.agent_run(id),
    session_id VARCHAR(64) NOT NULL REFERENCES sql_analyzer.analysis_session(id),
    type VARCHAR(50) NOT NULL,
    title VARCHAR(500) NOT NULL,
    description TEXT NOT NULL,
    problem TEXT NOT NULL DEFAULT '',
    impact TEXT NOT NULL DEFAULT '',
    priority VARCHAR(30) NOT NULL DEFAULT 'MEDIUM',
    evidence TEXT NOT NULL DEFAULT '{}',
    suggested_sql TEXT,
    suggested_ddl TEXT,
    confidence DOUBLE PRECISION NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL DEFAULT 'PROPOSED',
    version INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sql_analyzer.recommendation_feedback (
    id VARCHAR(64) PRIMARY KEY,
    recommendation_id VARCHAR(64) NOT NULL REFERENCES sql_analyzer.recommendation(id),
    client_id VARCHAR(64) NOT NULL REFERENCES sql_analyzer.client(id),
    decision VARCHAR(20) NOT NULL,
    category VARCHAR(80),
    reason TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT recommendation_decision_allowed CHECK (decision IN ('ACCEPTED','REJECTED')),
    CONSTRAINT rejected_feedback_requires_reason CHECK (
        decision <> 'REJECTED' OR length(trim(coalesce(reason, ''))) > 0
    )
);

-- ---------- Business knowledge ----------

CREATE TABLE sql_analyzer.knowledge_source (
    id VARCHAR(64) PRIMARY KEY,
    client_id VARCHAR(64) NOT NULL REFERENCES sql_analyzer.client(id),
    name VARCHAR(300) NOT NULL,
    source_type VARCHAR(40) NOT NULL DEFAULT 'EXCEL',
    current_version_id VARCHAR(64),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sql_analyzer.knowledge_version (
    id VARCHAR(64) PRIMARY KEY,
    source_id VARCHAR(64) NOT NULL REFERENCES sql_analyzer.knowledge_source(id) ON DELETE CASCADE,
    version_no INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',           -- DRAFT | PUBLISHED | ROLLED_BACK | FAILED
    artifact_id VARCHAR(64) REFERENCES sql_analyzer.artifact(id),
    preview_json TEXT NOT NULL DEFAULT '{}',
    error_json TEXT NOT NULL DEFAULT '[]',
    published_by VARCHAR(64),
    published_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (source_id, version_no)
);

CREATE INDEX idx_knowledge_version_source ON sql_analyzer.knowledge_version(source_id, version_no DESC);

CREATE TABLE sql_analyzer.kb_table_def (
    id VARCHAR(64) PRIMARY KEY,
    source_id VARCHAR(64) NOT NULL REFERENCES sql_analyzer.knowledge_source(id) ON DELETE CASCADE,
    version_id VARCHAR(64) NOT NULL REFERENCES sql_analyzer.knowledge_version(id) ON DELETE CASCADE,
    datasource VARCHAR(200),
    schema_name VARCHAR(200),
    table_name VARCHAR(300) NOT NULL,
    business_name VARCHAR(300),
    purpose TEXT,
    owner VARCHAR(200),
    data_domain VARCHAR(200),
    sheet_locator VARCHAR(200),
    active BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_kb_table_lookup ON sql_analyzer.kb_table_def(table_name, active);

CREATE TABLE sql_analyzer.kb_column_def (
    id VARCHAR(64) PRIMARY KEY,
    source_id VARCHAR(64) NOT NULL REFERENCES sql_analyzer.knowledge_source(id) ON DELETE CASCADE,
    version_id VARCHAR(64) NOT NULL REFERENCES sql_analyzer.knowledge_version(id) ON DELETE CASCADE,
    table_name VARCHAR(300) NOT NULL,
    column_name VARCHAR(300) NOT NULL,
    business_meaning TEXT,
    data_type VARCHAR(100),
    enum_domain VARCHAR(300),
    is_sensitive BOOLEAN NOT NULL DEFAULT FALSE,
    is_required BOOLEAN NOT NULL DEFAULT FALSE,
    sensitivity_policy VARCHAR(20) NOT NULL DEFAULT 'HASHED', -- PLAINTEXT | HASHED | OMITTED
    sheet_locator VARCHAR(200),
    active BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_kb_column_lookup ON sql_analyzer.kb_column_def(table_name, column_name, active);

CREATE TABLE sql_analyzer.kb_rule (
    id VARCHAR(64) PRIMARY KEY,
    source_id VARCHAR(64) NOT NULL REFERENCES sql_analyzer.knowledge_source(id) ON DELETE CASCADE,
    version_id VARCHAR(64) NOT NULL REFERENCES sql_analyzer.knowledge_version(id) ON DELETE CASCADE,
    rule_key VARCHAR(200),
    target VARCHAR(300),
    description TEXT,
    constraint_expr TEXT,
    priority INTEGER NOT NULL DEFAULT 100,
    effective_from TIMESTAMP WITH TIME ZONE,
    sheet_locator VARCHAR(200),
    active BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_kb_rule_lookup ON sql_analyzer.kb_rule(target, active);

CREATE TABLE sql_analyzer.kb_enum_value (
    id VARCHAR(64) PRIMARY KEY,
    source_id VARCHAR(64) NOT NULL REFERENCES sql_analyzer.knowledge_source(id) ON DELETE CASCADE,
    version_id VARCHAR(64) NOT NULL REFERENCES sql_analyzer.knowledge_version(id) ON DELETE CASCADE,
    enum_code VARCHAR(300) NOT NULL,
    display_name VARCHAR(300),
    meaning TEXT,
    is_valid BOOLEAN NOT NULL DEFAULT TRUE,
    sheet_locator VARCHAR(200),
    active BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_kb_enum_lookup ON sql_analyzer.kb_enum_value(enum_code, active);

CREATE TABLE sql_analyzer.kb_alias (
    id VARCHAR(64) PRIMARY KEY,
    source_id VARCHAR(64) NOT NULL REFERENCES sql_analyzer.knowledge_source(id) ON DELETE CASCADE,
    version_id VARCHAR(64) NOT NULL REFERENCES sql_analyzer.knowledge_version(id) ON DELETE CASCADE,
    alias_type VARCHAR(40) NOT NULL,                        -- TABLE | COLUMN | TERM
    alias_name VARCHAR(300) NOT NULL,
    target_name VARCHAR(300) NOT NULL,
    sheet_locator VARCHAR(200),
    active BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_kb_alias_lookup ON sql_analyzer.kb_alias(alias_name, active);

-- ---------- Index / sharding metadata ----------

CREATE TABLE sql_analyzer.index_def (
    id VARCHAR(64) PRIMARY KEY,
    datasource VARCHAR(200),
    schema_name VARCHAR(200),
    table_name VARCHAR(300) NOT NULL,
    index_name VARCHAR(300) NOT NULL,
    index_type VARCHAR(40) NOT NULL DEFAULT 'NORMAL',       -- NORMAL | UNIQUE | PRIMARY | FUNCTIONAL | PREFIX
    columns_json TEXT NOT NULL DEFAULT '[]',
    cardinality BIGINT,
    usage_count BIGINT,
    source VARCHAR(40) NOT NULL DEFAULT 'MANUAL',           -- SYSTEM_CATALOG | GOLDENDB_ADMIN | EXCEL | MANUAL
    confirmed_by VARCHAR(200),
    valid_from TIMESTAMP WITH TIME ZONE,
    version INTEGER NOT NULL DEFAULT 1,
    checksum CHAR(64),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_index_def_lookup ON sql_analyzer.index_def(table_name);

CREATE TABLE sql_analyzer.shard_def (
    id VARCHAR(64) PRIMARY KEY,
    datasource VARCHAR(200),
    logical_table VARCHAR(300) NOT NULL,
    physical_pattern VARCHAR(300),
    shard_key VARCHAR(300),
    secondary_shard_key VARCHAR(300),
    algorithm VARCHAR(200),
    routing_expr TEXT,
    topology_json TEXT NOT NULL DEFAULT '{}',
    source VARCHAR(40) NOT NULL DEFAULT 'MANUAL',           -- SYSTEM_CATALOG | GOLDENDB_ADMIN | EXCEL | MANUAL
    confirmed_by VARCHAR(200),
    valid_from TIMESTAMP WITH TIME ZONE,
    version INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_shard_def_lookup ON sql_analyzer.shard_def(logical_table);

CREATE TABLE sql_analyzer.metadata_conflict (
    id VARCHAR(64) PRIMARY KEY,
    entity_type VARCHAR(40) NOT NULL,                       -- INDEX | SHARD
    entity_key VARCHAR(600) NOT NULL,
    existing_json TEXT NOT NULL DEFAULT '{}',
    incoming_json TEXT NOT NULL DEFAULT '{}',
    source VARCHAR(40) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',          -- PENDING | RESOLVED | DISMISSED
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_metadata_conflict_status ON sql_analyzer.metadata_conflict(status, created_at);

-- ---------- Datasource profiles (read-only targets; secret via env reference) ----------

CREATE TABLE sql_analyzer.datasource_profile (
    id VARCHAR(64) PRIMARY KEY,
    client_id VARCHAR(64) NOT NULL REFERENCES sql_analyzer.client(id),
    name VARCHAR(300) NOT NULL,
    dialect VARCHAR(40) NOT NULL DEFAULT 'MYSQL',           -- MYSQL | GOLDENDB
    jdbc_url VARCHAR(600) NOT NULL,
    username VARCHAR(200),
    credential_env VARCHAR(200),
    read_only BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ---------- Profiling ----------

CREATE TABLE sql_analyzer.profiling_job (
    id VARCHAR(64) PRIMARY KEY,
    client_id VARCHAR(64) NOT NULL REFERENCES sql_analyzer.client(id),
    datasource_profile_id VARCHAR(64) NOT NULL REFERENCES sql_analyzer.datasource_profile(id),
    config_json TEXT NOT NULL DEFAULT '{}',
    status VARCHAR(30) NOT NULL DEFAULT 'QUEUED',           -- QUEUED | RUNNING | COMPLETED | FAILED | CANCELLED
    leased_by VARCHAR(200),
    lease_until TIMESTAMP WITH TIME ZONE,
    retry_count INTEGER NOT NULL DEFAULT 0,
    last_error TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_profiling_job_poll ON sql_analyzer.profiling_job(status, created_at);

CREATE TABLE sql_analyzer.profile_snapshot (
    id VARCHAR(64) PRIMARY KEY,
    job_id VARCHAR(64) NOT NULL REFERENCES sql_analyzer.profiling_job(id),
    datasource_profile_id VARCHAR(64) NOT NULL REFERENCES sql_analyzer.datasource_profile(id),
    status VARCHAR(30) NOT NULL DEFAULT 'RUNNING',
    config_json TEXT NOT NULL DEFAULT '{}',
    started_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE sql_analyzer.profile_column_stat (
    id VARCHAR(64) PRIMARY KEY,
    snapshot_id VARCHAR(64) NOT NULL REFERENCES sql_analyzer.profile_snapshot(id) ON DELETE CASCADE,
    schema_name VARCHAR(200),
    table_name VARCHAR(300) NOT NULL,
    column_name VARCHAR(300) NOT NULL,
    null_ratio DOUBLE PRECISION,
    approx_distinct BIGINT,
    min_value TEXT,
    max_value TEXT,
    top_k_json TEXT NOT NULL DEFAULT '[]',
    buckets_json TEXT NOT NULL DEFAULT '[]',
    quantiles_json TEXT NOT NULL DEFAULT '[]',
    collected_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_profile_column_stat_snapshot ON sql_analyzer.profile_column_stat(snapshot_id);

-- ---------- AgentScope state (H2) ----------
-- The official PostgresDistributedStore self-creates its own tables on PostgreSQL; on H2 the
-- product-provided persistent AgentStateStore + BaseStore (docs/cloud-code-next-goal.md §3.6)
-- use these Flyway-managed tables. Keyed by (user_id = authenticated clientId, session_id).

CREATE SCHEMA IF NOT EXISTS agentscope;

CREATE TABLE agentscope.agent_state (
    user_id VARCHAR(255) NOT NULL,
    session_id VARCHAR(255) NOT NULL,
    state_key VARCHAR(255) NOT NULL,
    item_index INTEGER NOT NULL DEFAULT 0,
    state_data TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, session_id, state_key, item_index)
);

-- NOTE: agentscope.kv_store is created by the portable common migration (version 10) on both
-- databases; the H2 AgentState table above has no PostgreSQL equivalent because the official
-- PostgresAgentStateStore self-creates its own table there.
