ALTER TABLE v2_recommendation ADD COLUMN IF NOT EXISTS problem TEXT NOT NULL DEFAULT '';
ALTER TABLE v2_recommendation ADD COLUMN IF NOT EXISTS impact TEXT NOT NULL DEFAULT '';
ALTER TABLE v2_recommendation ADD COLUMN IF NOT EXISTS priority VARCHAR(30) NOT NULL DEFAULT 'MEDIUM';
